using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace RoslynCodeLens.Analysis;

/// <summary>
/// Detects whether a syntax tree represents auto-generated code.
/// Used by analysis tools to skip tool-generated files (compiler / source generators / IDE designers).
/// </summary>
public static class GeneratedCodeDetector
{
    public static bool IsGenerated(SyntaxTree tree)
    {
        var path = tree.FilePath;
        if (!string.IsNullOrEmpty(path))
        {
            if (path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)) return true;
            if (path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)) return true;
        }

        var text = tree.GetText();
        var headerLength = Math.Min(text.Length, 1024);
        var header = text.GetSubText(new TextSpan(0, headerLength)).ToString();
        return header.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase);
    }
}
