// <auto-generated>
//     This is a fixture for verifying that generate_test_skeleton refuses
//     generated-code targets. Do not hand-edit semantics here.
// </auto-generated>

namespace TestLib;

public class GeneratedTarget
{
    public void DoWork() { }
}
